export enum UserRole {
  USER = 'USER',
  COMPANY = 'COMPANY',
  ADMIN = 'ADMIN',
}

export enum ReviewStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  RESOLUTION_PENDING = 'RESOLUTION_PENDING',
  MODIFIED = 'MODIFIED',
  WITHDRAWN = 'WITHDRAWN',
  PROCEEDED = 'PROCEEDED',
  DELETED = 'DELETED',
}

export enum ReviewReplyStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum CompanyProjectStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum ModerationAction {
  AUTO_APPROVED = 'AUTO_APPROVED',
  QUEUED = 'QUEUED',
  MANUAL_APPROVED = 'MANUAL_APPROVED',
  MANUAL_REJECTED = 'MANUAL_REJECTED',
  MANUAL_RESOLVE = 'MANUAL_RESOLVE',
  RESOLUTION_PROCEEDED = 'RESOLUTION_PROCEEDED',
  RESOLUTION_WITHDRAWN = 'RESOLUTION_WITHDRAWN',
  RESOLUTION_MODIFIED = 'RESOLUTION_MODIFIED',
  FLAGGED = 'FLAGGED',
}

export enum Locale {
  EN = 'en',
  AR = 'ar',
}
